---
# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# Find more information at:
# https://github.com/microsoft/msvc-code-analysis-action

name: Microsoft C++ Code Analysis

on: # yamllint disable-line rule:truthy
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '37 6 * * 0'

env:
  # Path to the CMake build directory.
  build: '${{ github.workspace }}/build'

permissions:
  contents: read

jobs:
  analyze:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
    name: Analyze
    runs-on: windows-2019

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up cache directory for Hunter package manager
        uses: actions/cache@v3
        with:
          path: ${{ runner.temp }}/.hunter-cache
          key: msvc-${{ runner.os }}-hunter-v1-${{ hashFiles('**/CMakeLists.txt', '**/*.cmake') }}
          restore-keys: |
            msvc-${{ runner.os }}-hunter-v1-

      - name: Set Hunter cache directory
        shell: sh
        run: |
          echo "HUNTER_ROOT=$RUNNER_TEMP/.hunter-cache" >> "$GITHUB_ENV"

      - name: Configure CMake
        run: cmake -B ${{ env.build }}

      # Build is not required unless generated source files are used
      # - name: Build CMake
      #   run: cmake --build ${{ env.build }}

      - name: MSVC Code Analysis
        uses: microsoft/msvc-code-analysis-action@v0.1.0
        # Provide a unique ID to access the sarif output path
        id: run-analysis
        with:
          cmakeBuildDirectory: ${{ env.build }}
          buildConfiguration: Debug
          # Ruleset file that will determine what checks will be run
          ruleset: NativeRecommendedRules.ruleset
          # Any includes contained inside these paths will be excluded from analysis
          ignoredIncludePaths: ${{ github.workspace }}/dependency

      # Upload SARIF file to GitHub Code Scanning Alerts
      - name: Upload SARIF to GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ steps.run-analysis.outputs.sarif }}

      # Upload SARIF file as an Artifact to download and view
      - name: Upload SARIF as an Artifact
        uses: actions/upload-artifact@v2
        with:
          name: sarif-file.json
          path: ${{ steps.run-analysis.outputs.sarif }}
